require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'
    - 'db/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'

Layout/ClassStructure:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Max: 95
  Exclude:
    - 'bin/delayed_job'
    - 'bin/spring'
    - 'config/application.rb'
    - 'config/initializers/devise.rb'
    - 'db/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/models/country_spec.rb'

Rails/SkipsModelValidations:
  Exclude:
  - 'app/services/admin/announcement_notifications_creator.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/*.rb'

Style/CombinableLoops:
  Exclude:
    - 'db/seeds.rb'

Style/GuardClause:
  Exclude:
    - 'spec/support/*.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
