require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-md

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'
    - 'db/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 85
  Exclude:
    - 'bin/delayed_job'
    - 'bin/spring'
    - 'config/application.rb'
    - 'config/initializers/devise.rb'
    - 'db/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/models/country_spec.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/*.rb'

Style/GuardClause:
  Exclude:
    - 'spec/support/*.rb'
