default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: countryfier_dev
  host: 127.0.0.1
  port: 3307
  password: <%= ENV['DB_PASSWORD'] %>
  username: <%= ENV['DB_USERNAME'] %>

test:
  <<: *default
  database: countryfier_test
  host: 127.0.0.1
  port: 3307
  password: <%= ENV['DB_PASSWORD'] %>
  username: <%= ENV['DB_USERNAME'] %>
