default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: countryfier_dev
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>

test:
  <<: *default
  database: countryfier_test
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB_NAME'] %>
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
