development:
  secret_key_base: <%= ENV['TEST_SECRET_KEY_BASE'] %>
  jwt_secret_key_base: <%= ENV['TEST_JWT_SECRET_KEY_BASE'] %>

test:
  secret_key_base: <%= ENV['TEST_SECRET_KEY_BASE'] %>
  jwt_secret_key_base: <%= ENV['TEST_JWT_SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_secret_key_base: <%= ENV['JWT_SECRET_KEY_BASE'] %>
