name: CD

env:
  RUBY_VERSION: 3.0

on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.head_ref || github.run_id }}-cd
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    needs: [ test, lint ]

    steps:
      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host countrify
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes
              User deploy

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.gitRef.outputs.sha }}
          persist-credentials: false

      - name: Read .ruby-version
        run: echo "##[set-output name=RUBY_VERSION;]$(cat .ruby-version)"
        id: ruby_version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ steps.ruby_version.outputs.RUBY_VERSION }}"
          bundler-cache: true

      - name: Deploy to production
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap production deploy
