name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: gitleaks-action # https://github.com/marketplace/actions/gitleaks
      uses: zricethezav/gitleaks-action@master
    - name: rubocop # https://github.com/andrewmcodes/rubocop-linter-action
      uses: gimenete/rubocop-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5 # https://github.com/actions/setup-ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: build and test with rspec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
